# Stolen from cbkadal's repo

title:       "Sistem Operasi 2021-1 (OS211)"
description: "Halo!"
author:           "Bintang Dominique"
address:          "Jakarta"
sitemap:          "true"
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
urlweb:           "https://os.bintangdom.com/"
urlgithub:        "https://github.com/bintangdom/WebApp/"
urlghpage:        "https://bintangdom.github.io/WebApp/"
keywords:         "jekyll, testing"
github:           [metadata]
